name: shared_core
description: Shared core package for Orient Mobile apps
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/logo.png
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 300
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 700
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Variable.ttf
          weight: 800
